version: "3"
services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - ./client:/client/
      - .client:/client/node_modules

  server:
    build: 
      context: ./
      dockerfile: Dockerfile-server
    ports:
      - "4000:4000"