FROM node:10
 
WORKDIR /usr/src/app
 
# Copies package.json and package-lock.json to Docker environment
COPY client/package*.json ./
 
# Installs all node packages
RUN npm install
 
# Copies everything over to Docker environment
COPY ./client .
 
# Uses port which is used by the actual application
EXPOSE 3000
 
# Finally runs the application
CMD [ "npm", "start" ]